// This file is automatically generated by qtc from "button.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/button.qtpl:1
package templates

//line templates/button.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/button.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/button.qtpl:1
func StreamButtonPage(qw422016 *qt422016.Writer, data ButtonData) {
	//line templates/button.qtpl:1
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
  </head>  <body>
    <h1>Glip bot Tokenizer</h1>

    <p>Install your Glip Bot</p>

	<div style="margin-top:1em"><a href="https://www.ringcentral.com/apps/`)
	//line templates/button.qtpl:12
	qw422016.E().S(data.ApplicationID)
	//line templates/button.qtpl:12
	qw422016.N().S(`/install?landing_url=https%3A%2F%2Fglipbot-tokenizer.herokuapp.com%2Faccess_token" style="box-sizing:border-box;display: inline-block;border: 1px solid #0073ae;border-radius: 4px;text-decoration: none;height: 60px;line-height: 60px;width: 160px;padding-left: 20px;font-size: 14px;color:#0073ae;font-family:"Lato",Helvetica,Arial,sans-serif"><span>Add to </span><img style="width: 68px;vertical-align: middle;display: inline-block;margin-left: 10px;" src="https://netstorage.ringcentral.com/dpw/common/glip/logo_glip.png"></a></div>

    <hr/>
    <a href="https://github.com/grokify/glipbot-tokenizer">https://github.com/grokify/glipbot-tokenizer</a>
  </body>
</html>
`)
//line templates/button.qtpl:18
}

//line templates/button.qtpl:18
func WriteButtonPage(qq422016 qtio422016.Writer, data ButtonData) {
	//line templates/button.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/button.qtpl:18
	StreamButtonPage(qw422016, data)
	//line templates/button.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line templates/button.qtpl:18
}

//line templates/button.qtpl:18
func ButtonPage(data ButtonData) string {
	//line templates/button.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/button.qtpl:18
	WriteButtonPage(qb422016, data)
	//line templates/button.qtpl:18
	qs422016 := string(qb422016.B)
	//line templates/button.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/button.qtpl:18
	return qs422016
//line templates/button.qtpl:18
}
