// This file is automatically generated by qtc from "home.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line templates/home.qtpl:1
package templates

//line templates/home.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/home.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/home.qtpl:1
func StreamHomePage(qw422016 *qt422016.Writer) {
	//line templates/home.qtpl:1
	qw422016.N().S(`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
  </head>
  <script type="text/javascript">

// https://stackoverflow.com/questions/4907843/open-a-url-in-a-new-tab-and-not-a-new-window-using-javascript
function openInNewTab(url) {
  var win = window.open(url, '_blank');
  win.focus();
}

function openGlipBot(appId) {
  if (appId.length == 0) {
    alert("Please enter your Application Id");
    return;
  }
  var url = 'https://www.ringcentral.com/apps/' + appId + 
    '/install?landing_url=https%3A%2F%2Fglipbot-tokenizer.herokuapp.com%2Faccess_token';
  openInNewTab(url);
}

  </script>
  <body>
    <h1>Glip bot Tokenizer</h1>

    <p>Get your private Glip bot token.</p>

    <form action="/button" method="post">

      <p><input type="text" id="appId" name="appId" value="" placeholder="Your Bot App Id" style="width:400px" /></p>
      <p><input type="text" id="clientId" name="clientId" value="" placeholder="Your Bot Client Id" style="width:400px" /></p>
      <p><input type="text" id="clientSecret" name="clientSecret" value="" placeholder="Your Bot Client Secret" style="width:400px" /></p>
      <p><select name="serverUrl">
      <option value="https://platform.ringcentral.com">https://platform.ringcentral.com</option>
      <option value="https://platform.devtest.ringcentral.com">https://platform.devtest.ringcentral.com</option>
      </select></p>

      <input type="submit" value="Next" />

    </form>

    <hr/>
    <a href="https://github.com/grokify/glipbot-tokenizer">https://github.com/grokify/glipbot-tokenizer</a>
  </body>
</html>
`)
//line templates/home.qtpl:50
}

//line templates/home.qtpl:50
func WriteHomePage(qq422016 qtio422016.Writer) {
	//line templates/home.qtpl:50
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line templates/home.qtpl:50
	StreamHomePage(qw422016)
	//line templates/home.qtpl:50
	qt422016.ReleaseWriter(qw422016)
//line templates/home.qtpl:50
}

//line templates/home.qtpl:50
func HomePage() string {
	//line templates/home.qtpl:50
	qb422016 := qt422016.AcquireByteBuffer()
	//line templates/home.qtpl:50
	WriteHomePage(qb422016)
	//line templates/home.qtpl:50
	qs422016 := string(qb422016.B)
	//line templates/home.qtpl:50
	qt422016.ReleaseByteBuffer(qb422016)
	//line templates/home.qtpl:50
	return qs422016
//line templates/home.qtpl:50
}
